# -*- coding: utf-8 -*-
#############################################################################
#    A part of Open HRMS Project <https://www.openhrms.com>
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions(<https://www.cybrosys.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
from odoo import fields, models, _
from odoo.exceptions import UserError


class HrPayslipRun(models.Model):
    """Extends the standard 'hr.payslip.run' model to include additional fields
    for managing payroll runs.
    Methods:
        compute_total_amount: Compute the total amount of the payroll run."""
    _inherit = 'hr.payslip.run'

    journal_id = fields.Many2one(comodel_name='account.journal',
                                 string='Salary Journal',
                                 required=True, help="Journal associated with "
                                                     "the record",
                                 default=lambda self: self.env[
                                     'account.journal'].search(
                                     [('type', '=', 'general')],
                                     limit=1))
    move_count = fields.Integer(compute='_compute_move_count', string='Journal Entries')
    payment_count = fields.Integer(compute='_compute_payment_count', string='Payments')

    def _compute_payment_count(self):
        """Compute the total number of payments linked to this payslip run."""
        for run in self:
            run.payment_count = self.env['account.payment'].search_count([('memo', 'in', run.slip_ids.mapped('number'))])

    def action_register_payment(self):
        """Register payments sequentially for all confirmed payslips in the run."""
        self.ensure_one()
        for slip in self.slip_ids.filtered(lambda s: s.state == 'done'):
            slip.action_register_payment()
        return True

    def action_open_payments(self):
        """Open the tree view displaying all payments associated with this run's payslips."""
        self.ensure_one()
        payments = self.env['account.payment'].search([('memo', 'in', self.slip_ids.mapped('number'))])
        return {
            'name': _('Payments'),
            'type': 'ir.actions.act_window',
            'res_model': 'account.payment',
            'view_mode': 'list,form',
            'domain': [('id', 'in', payments.ids)],
        }

    def action_open_payment_wizard(self):
        """Open the batch payment wizard to register payments for the confirmed payslips in this run."""
        self.ensure_one()
        
        # Verify that there are slips and they have posted entries
        slips = self.slip_ids.filtered(lambda s: s.state == 'done')
        if not slips:
            raise UserError(_("There are no confirmed payslips in this batch."))
            
        for slip in slips:
            if not slip.move_id or slip.move_id.state != 'posted':
                raise UserError(_("You can only register payment for posted journal entries. Payslip '%s' has an unposted entry.") % slip.name)
                
        action = self.env["ir.actions.actions"]._for_xml_id("hr_payroll_account_community.action_hr_batch_payment_wizard")
        action['context'] = {
            'active_model': 'hr.payslip.run',
            'active_ids': self.ids,
        }
        return action

    def _compute_move_count(self):
        """Compute the total number of journal entries generated by the payslips in this run."""
        for run in self:
            run.move_count = len(run.mapped('slip_ids.move_id'))

    def action_open_journal_entries(self):
        """Open the tree view displaying all accounting journal entries associated with this run."""
        self.ensure_one()
        moves = self.mapped('slip_ids.move_id')
        action = self.env["ir.actions.actions"]._for_xml_id("account.action_move_journal_line")
        action['domain'] = [('id', 'in', moves.ids)]
        action['context'] = {'default_journal_id': self.journal_id.id}
        return action
